// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyvjpTRg1UFgb8fh9cp1HveeURv-NjCtk',
    appId: '1:1046056106009:web:f6e34eedfb170b4a235288',
    messagingSenderId: '1046056106009',
    projectId: 'splitify-eae5e',
    authDomain: 'splitify-eae5e.firebaseapp.com',
    storageBucket: 'splitify-eae5e.firebasestorage.app',
    measurementId: 'G-G46ZVPD60Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzT0P_mR-QflCTfVAG-qSKB5vuSQMokFo',
    appId: '1:1046056106009:android:a0b66a075d6b55ae235288',
    messagingSenderId: '1046056106009',
    projectId: 'splitify-eae5e',
    storageBucket: 'splitify-eae5e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDI4iOnPqg1xjk82Gceddau7Sh4VP_rmio',
    appId: '1:1046056106009:ios:eaa967fb716af9a9235288',
    messagingSenderId: '1046056106009',
    projectId: 'splitify-eae5e',
    storageBucket: 'splitify-eae5e.firebasestorage.app',
    iosBundleId: 'com.example.splitify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDI4iOnPqg1xjk82Gceddau7Sh4VP_rmio',
    appId: '1:1046056106009:ios:eaa967fb716af9a9235288',
    messagingSenderId: '1046056106009',
    projectId: 'splitify-eae5e',
    storageBucket: 'splitify-eae5e.firebasestorage.app',
    iosBundleId: 'com.example.splitify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCyvjpTRg1UFgb8fh9cp1HveeURv-NjCtk',
    appId: '1:1046056106009:web:25fc0c6cf1aacb7a235288',
    messagingSenderId: '1046056106009',
    projectId: 'splitify-eae5e',
    authDomain: 'splitify-eae5e.firebaseapp.com',
    storageBucket: 'splitify-eae5e.firebasestorage.app',
    measurementId: 'G-5CXS5096V7',
  );
}
